openapi: 3.0.3
info:
  title: Ebony API
  description: Draft Call and JSON of the API that will support the ebony FE
  version: 1.0.0
  contact: {}
servers:
  - url: 'https://61d1d532-0f66-45c3-9a78-d90bdc274fbe.mock.pstmn.io'
paths:
  /user/Auth:
    post:
      tags:
        - Login
      summary: Login
      description: Login
      operationId: login
      responses:
        '200':
          description: ''
  /user/refresh:
    post:
      tags:
        - Login
      summary: Login refresh
      description: Login refresh
      operationId: loginRefresh
      responses:
        '200':
          description: ''
  /dev:
    get:
      tags:
        - Developer
      summary: Get Dev List
      description: Get Dev List
      operationId: getDevList
      parameters:
        - name: jwt
          in: header
          schema:
            type: string
            example: Batman
      responses:
        '200':
          description: ''
    post:
      tags:
        - Developer
      summary: Amend Dev
      description: Amend Dev
      operationId: amendDev
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                addRegions:
                  type: array
                  items:
                    type: object
                    properties:
                      accountNo:
                        type: string
                        example: '65436543'
                      branchName:
                        type: string
                        example: bond rd
                      regionName:
                        type: string
                        example: southeast London
                  example:
                    - accountNo: '65436543'
                      branchName: bond rd
                      regionName: southeast London
                devId:
                  type: number
                  example: 12345
            example:
              addRegions:
                - accountNo: '65436543'
                  branchName: bond rd
                  regionName: southeast London
              devId: 12345
      responses:
        '200':
          description: ''
  /product/search:
    get:
      tags:
        - Product
      summary: Product search
      description: Product search
      operationId: productSearch
      parameters:
        - name: searchTerm
          in: query
          schema:
            type: string
            example: copper pipe
      responses:
        '200':
          description: ''
  /bom/upload:
    post:
      tags:
        - BOM
      summary: Upload BOM
      description: Upload BOM
      operationId: uploadBom
      responses:
        '200':
          description: ''
  /bom:
    put:
      tags:
        - BOM
      summary: Amend BOM
      description: Amend BOM
      operationId: amendBom
      responses:
        '200':
          description: ''
    post:
      tags:
        - BOM
      summary: BOM Create
      description: BOM Create
      operationId: bomCreate
      responses:
        '200':
          description: ''
  /dev/234567/houseType:
    get:
      tags:
        - BOM
      summary: Get House Types
      description: Get House Types
      operationId: getHouseTypes
      responses:
        '200':
          description: ''
  /dev/234567/bom/234567:
    get:
      tags:
        - BOM
      summary: GET BOM
      description: GET BOM
      operationId: getBom
      responses:
        '200':
          description: GET BOM
          content:
            application/json:
              schema:
                type: object
                properties:
                  bom:
                    type: string
                    example: green house - lux
                  bomDescriptoin:
                    type: string
                    example: this is a bom
                  bomId:
                    type: number
                    example: 234567
                  bomItems:
                    type: array
                    items:
                      type: object
                      properties:
                        bomItemId:
                          type: number
                          example: 98765
                        deliverGroup:
                          type: number
                          example: 2
                        description:
                          type: string
                          example: a real nice pipe
                        fix:
                          type: number
                          example: 2
                        itemId:
                          type: number
                          example: 7654
                        name:
                          type: string
                          example: pvc pipe 10x4
                        qty:
                          type: number
                          example: 4
                    example:
                      - bomItemId: 98765
                        deliverGroup: 2
                        description: a real nice pipe
                        fix: 2
                        itemId: 7654
                        name: pvc pipe 10x4
                        qty: 4
                      - bomItemId: 98766
                        deliverGroup: 1
                        description: a real nice gutter
                        fix: 1
                        itemId: 7655
                        name: gutter
                        qty: 1
                  houseTyp:
                    type: string
                    example: green house
                  houseTypId:
                    type: number
                    example: 435265
              examples:
                GET BOM:
                  value:
                    bom: green house - lux
                    bomDescriptoin: this is a bom
                    bomId: 234567
                    bomItems:
                      - bomItemId: 98765
                        deliverGroup: 2
                        description: a real nice pipe
                        fix: 2
                        itemId: 7654
                        name: pvc pipe 10x4
                        qty: 4
                      - bomItemId: 98766
                        deliverGroup: 1
                        description: a real nice gutter
                        fix: 1
                        itemId: 7655
                        name: gutter
                        qty: 1
                    houseTyp: green house
                    houseTypId: 435265
  /dev/order:
    put:
      tags:
        - Order
      summary: Amend Order
      description: Amend Order
      operationId: amendOrder
      responses:
        '200':
          description: ''
    post:
      tags:
        - Order
      summary: Create Draft Order
      description: Create Draft Order
      operationId: createDraftOrder
      responses:
        '200':
          description: ''
  /dev/order/quote:
    post:
      tags:
        - Order
      summary: Export Draft
      description: Export Draft
      operationId: exportDraft
      responses:
        '200':
          description: ''
  /dev/12345/site:
    get:
      tags:
        - Order
      summary: Get Sites
      description: Get Sites
      operationId: getSites
      responses:
        '200':
          description: ''
  /dev/12345/site/23455:
    get:
      tags:
        - Order
      summary: Get site
      description: Get site
      operationId: getSite
      responses:
        '200':
          description: ''
  /dev/12345/site/23455/plot/54345:
    get:
      tags:
        - Order
      summary: Get site plots
      description: Get site plots
      operationId: getSitePlots
      responses:
        '200':
          description: ''
  /dev/order/confirm:
    post:
      tags:
        - Order
      summary: Confirm Order
      description: Confirm Order
      operationId: confirmOrder
      responses:
        '200':
          description: ''
  /dev/order/schedule:
    post:
      tags:
        - Order
      summary: Amend Schedule
      description: Amend Schedule
      operationId: amendSchedule
      responses:
        '200':
          description: ''
tags:
  - name: Login
  - name: Developer
  - name: Product
  - name: BOM
  - name: Order
